### ISSUE TITLE
add "show hashes" to regular directory list.

### ISSUE THREAD

**Issue by simsong** [digitalcorpora/digitalcorpora_app#59]

**Comment by ajnelson-nist** [comment]
Hi @simsong ,

[PR 60](https://github.com/digitalcorpora/digitalcorpora_app/pull/60) obscured two things:
* Hashes are now optionally displayed, requiring a user click to enable.
* TImestamp time zones are now completely removed.

I think both of these are a step backward in functionality, and I'd like to request they be restored.  I filed [PR 61](https://github.com/digitalcorpora/digitalcorpora_app/pull/61) to restore time zones and prevent local-time vs UTC confusion.  I don't understand what the motivation was for hiding time zones altogether, but if it was page width, then I suggest `Z` is a good compromise for width vs prevent ambiguity.

Was page width also the reason for setting hash displays to toggle?

**Comment by simsong** [comment]
Z has been added.
Although you can show hashes, you now have a report that downloads _all_ hashes, so I'll be closing this.

(ps: even when you couldn't _see_ the hashes, they were still there in the HTML, so you could have viewed them programmatically.)
